[project]
name = "flask-app"
version = "0.1.0"
description = "A simple Flask application."

readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev-requirements = {file = "flask_app/dev-requirements.txt"}
